using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;

namespace Dignite.Vault.Extract.Documents.Pipelines;

/// <summary>
/// Outbound surface for <see cref="DocumentPipelineRunDto"/> (#216: split out from
/// <c>DocumentDto.PipelineRuns</c>). The first version exposes only "list all runs for a specified
/// documentId", the minimal dependency for pipeline status rows on the frontend document detail page.
/// Future increments can add cross-document query surfaces as needed, such as operations diagnostics
/// dashboards filtering failed runs by status or aggregating by time window.
/// <para>
/// Route is generated by ABP Auto API Controllers convention: a single Guid parameter becomes query
/// string, i.e. <c>GET /api/vault-extract/document-pipeline-runs?documentId=...</c>.
/// </para>
/// </summary>
public interface IDocumentPipelineRunAppService : IApplicationService
{
    /// <summary>
    /// Returns all pipeline runs for <paramref name="documentId"/>, ordered by
    /// (PipelineCode, AttemptNumber). Permission: <c>ExtractPermissions.Documents.Default</c>.
    /// Tenant isolation is automatically applied by the ABP <c>IMultiTenant</c> global filter.
    /// Nonexistent or cross-tenant documents throw <c>EntityNotFoundException</c>.
    /// </summary>
    Task<List<DocumentPipelineRunDto>> GetListAsync(Guid documentId);
}
